fix: android

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,18 +1,32 @@
 workflows:
-  build_android:
-    name: Build React Native Android APK
+  react-native-android:
+    name: React Native Android
+    max_build_duration: 120
+    instance_type: mac_mini_m2
     environment:
+      groups:
+        - google_play
       vars:
-        NODE_VERSION: 18.18.0  # Adjust based on your React Native version
-      working_directory: "."
+        PACKAGE_NAME: "com.sinmichael.sample.reactnative"
     scripts:
-      - name: Install Dependencies
-        script: yarn install
-      - name: Clean Android Build
-        script: cd android && ./gradlew clean && cd ..
-      - name: Set Up Gradle Properties
-        script: |
-      - name: Build Android APK
-        script: cd android && ./gradlew assembleRelease
+      - name: Set Android SDK location
+        script: | 
+          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+      - name: Install npm dependencies
+        script: | 
+          npm install
+      - name: Build Android release
+        script: | 
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+          fi
+          cd android
+          ./gradlew bundleRelease \
+            -PversionCode=$UPDATED_BUILD_NUMBER \
+            -PversionName=1.0.$UPDATED_BUILD_NUMBER
     artifacts:
-      - android/app/build/outputs/apk/release/app-release.apk
+      - android/app/build/outputs/**/*.aab
