fix: formatting

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,18 +1,35 @@
 workflows:
-    sample-workflow:
-        name: Codemagic Sample Workflow
-        max_build_duration: 120
-        instance_type: mac_mini_m2
-scripts:
-    - name: Install npm dependencies
-        script: | 
-            npm install
+  sample-workflow:
+    name: Codemagic Sample Workflow
+    max_build_duration: 120
+    instance_type: mac_mini_m2
+  scripts:
     - name: Set Android SDK location
-        script: | 
-            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+      script: |
+        echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+    - name: Install npm dependencies
+      script: |
+        npm install
+    - name: Run Expo Prebuild
+      script: |
+        npx expo prebuild
+    - name: Set up app/build.gradle
+      script: |
+        mv ./support-files/build.gradle android/app
     - name: Build Android release
-        script: | 
-            cd android
-            ./gradlew bundleRelease
-artifacts:
+      script: |
+        LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+        if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+            # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+        else
+            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+        fi
+        cd android
+        ./gradlew bundleRelease \
+          -PversionCode=$UPDATED_BUILD_NUMBER \
+          -PversionName=1.0.$UPDATED_BUILD_NUMBER
+  artifacts:
     - android/app/build/outputs/**/*.aab
+artifacts:
+  - android/app/build/outputs/**/*.aab
